### ISSUE TITLE
Push to rubygems.org

### ISSUE THREAD

**Issue by linjunpop** [adjust/nvd3-rails#3]
Is there any reason not to push this gem to rubygems.org?

**Comment by rapimo** [comment]
as you can see from the Readme it depends on submodules I'm not sure how to do that on rubygems.
As the underlaying nvd3 lib is still under heavy development we'd have to update to frequently.
However I'll think about it.

**Comment by nneal** [comment]
https://github.com/NealKemp/nvd3-rails
https://rubygems.org/gems/nvd3-rails

hope that helps!

**Comment by tmikoss** [comment]
I also have a gem that packages external library - implemented [a build process of sorts](https://github.com/tmikoss/openlayers-rails/blob/master/Rakefile) there. When there are changes in the source project, pull them in your repository from submodule, release. Maybe you could do something like that here.

**Comment by omnikron** [comment]
@nneal we've updated nvd3-rails/master to use the latest nvd3 from novus (with d3.v3.js which offers significant performance improvements among others ) - this is just a heads up in case you would like to update your fork to this version and make a release on rubygems.  It isn't backwards compatible in all cases which is why we've bumped the version to 1.0.0

**Comment by nneal** [comment]
thanks for the reminder!
